# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Censorship Global Studies Project
email: 2016tcyrus@tjhsst.edu
description: 2015-16 Bourjaily/Boswell Global Studies
baseurl: "/global-studies" # the subpath of your site, e.g. /blog
url: "http://tcyrus.github.io" # the base hostname & protocol for your site
github_username: tcyrus
